PLAT-520 Clean env vars
jembi/cares-disi-on-platform pull request #2
Opened 2022-10-03 08:38 UTC by nour-borgi

2022-10-03 10:38 UTC, Mark-Labuschagne approved these changes

2022-10-04 14:23 UTC, michaelloosen requested changes

2022-10-04 14:25 UTC, nour-borgi commented on .env.local
>  STATEFUL_NODES=single
thanks done :)

2022-10-04 14:27 UTC, michaelloosen approved these changes
LGTM

2022-10-04 15:56 UTC, merged